training:
  batch_size: 16
  transforms:
    - name: RandomRotation
      args:
        - 30
    - name: RandomResizedCrop
      args:
        - 224
    - name: RandomHorizontalFlip
    - name: ToTensor
    - name: Normalize
      args:
        - - 0.485
          - 0.456
          - 0.406
        - - 0.229
          - 0.224
          - 0.225
validation:
  batch_size: 16
  transforms:
    - name: Resize
      args:
        - 225
    - name: CenterCrop
      args:
        - 224
    - name: ToTensor
    - name: Normalize
      args:
        - - 0.485
          - 0.456
          - 0.406
        - - 0.229
          - 0.224
          - 0.225
